[alias]
shapes = "run -p shape-rs --example shapes"
pr = "run -p shape-rs --example shapes --release"
ptest = "test -p shape-rs ngon"
asm = "objdump -p shape-rs --release --example shapes -- -d --no-show-raw-insn"